# Generated by Django 5.0.1 on 2024-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cat_image', models.ImageField(blank=True, upload_to='MEDIA/categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Catgories',
            },
        ),
    ]
